### PR TITLE
tweaked the search so that the query updates as you type

### PR DESCRIPTION
**Pull request by TejjyMK**

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey @TejjyMK 
Can you please send the source code instead of the compiled file?
The compiled file is generated automatically.

**Comment by TejjyMK** [comment]
my bad.

can you see the updated info.plist ?

**Comment by gilbarbara** [comment]
@TejjyMK 

Not sure if I understand the whole `the query updates as you type`.
The workflow already updates the results when you type. I've installed this version locally and couldn't see any changes

**Comment by gilbarbara** [comment]
Closing due to inactivity

**Pull request closed without merging**
